title: Reproducible code for Trost et al., 2024 "A continental-scale analysis of riverine particulate biogeochemistry"
description: Code for processing National Ecological Observation Network (NEON) data of stream particulate and dissolved chemistry with boosted regression trees (BRT) machine learning modeling. 

publisher_text: 
publisher_url: 

license_text: 
license_url: 

frequency: 

certificate_embed: 
